name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed ATOSScompact.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: script-windows-exe
          path: dist/script.exe
          # optional: wie lange aufbewahren
          # retention-days: 7
