name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE (no UPX)
        shell: bash
        run: |
          pyinstaller --onefile --windowed --noupx --clean ATOSScompact.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: script-windows-exe
          path: dist/ATOSScompact.exe
          # optional: kürzere Aufbewahrungszeit
          # retention-days: 7
