name: Build and Upload Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed script.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-windows-exe
          path: dist/script.exe
          # optional: kürzere Aufbewahrungsdauer
          # retention-days: 7
